development:
  adapter: async

test:
  adapter: test

production:
  adapter: <%= ENV['REDIS_URL'].present? ? 'redis' : 'async' %>
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: glt_api_production